# Nível 1
**Passo 1 — Array de peças vendidas**

In [ ]:
import numpy as np

pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])

print(pecas_vendidas)

[150 120  90 210 300 250 180]


**Passo 2 — Faturamento diário**

In [ ]:
preco_medio = 50

faturamento = pecas_vendidas * preco_medio

print("Faturamento diário:")
print(faturamento)

Faturamento diário:
[ 7500  6000  4500 10500 15000 12500  9000]


**Passo 3 — Dias com mais de 200 peças**

In [ ]:
mascara = pecas_vendidas > 200

dias_pico = pecas_vendidas[mascara]

print("Máscara:")
print(mascara)

print("\nVendas acima de 200 peças:")
print(dias_pico)

Máscara:
[False False False  True  True  True False]

Vendas acima de 200 peças:
[210 300 250]


# Nível 2
**Passo 1 — Matriz das três lojas**

In [ ]:
import numpy as np

vendas = np.array([
    [200, 220, np.nan, 250],
    [150, 180, 160, 190],
    [300, 310, 290, 330]
])

print(vendas)

[[200. 220.  nan 250.]
 [150. 180. 160. 190.]
 [300. 310. 290. 330.]]


**Passo 2 — Total vendido por loja**

In [ ]:
total_por_loja = np.nansum(vendas, axis=1)

print("Total vendido por loja:")
print(total_por_loja)

Total vendido por loja:
[ 670.  680. 1230.]


**Passo 3 — Média ignorando nan**

In [ ]:
media_geral = np.nanmean(vendas)

print("Média diária geral da rede:")
print(media_geral)

Média diária geral da rede:
234.54545454545453


**Passo 4 — Meta atingida ou abaixo**

In [ ]:
resultado_meta = np.where(
    vendas >= 200,
    "Meta Atingida",
    "Abaixo"
)

print(resultado_meta)

[['Meta Atingida' 'Meta Atingida' 'Abaixo' 'Meta Atingida']
 ['Abaixo' 'Abaixo' 'Abaixo' 'Abaixo']
 ['Meta Atingida' 'Meta Atingida' 'Meta Atingida' 'Meta Atingida']]


# Nível 3
**Passo 1 — Gerar 50 vendas aleatórias**

In [ ]:
import numpy as np

rng = np.random.default_rng(42)

departamentos = np.array([
    "Eletrônicos",
    "Roupas",
    "Casa"
])

vendas = rng.choice(departamentos, size=50)

print("Vendas geradas:")
print(vendas)

Vendas geradas:
['Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas' 'Casa' 'Eletrônicos'
 'Casa' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Casa' 'Casa' 'Casa' 'Casa'
 'Casa' 'Roupas' 'Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas'
 'Eletrônicos' 'Casa' 'Casa' 'Roupas' 'Roupas' 'Casa' 'Roupas' 'Roupas'
 'Roupas' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Casa' 'Eletrônicos' 'Casa'
 'Casa' 'Eletrônicos' 'Roupas' 'Eletrônicos' 'Casa' 'Casa' 'Roupas'
 'Eletrônicos' 'Casa' 'Roupas' 'Casa' 'Casa' 'Casa']


**Passo 2 — Contagem por departamento**

In [ ]:
categorias, contagens = np.unique(
    vendas,
    return_counts=True
)

print("Volume de vendas por departamento:")

for categoria, quantidade in zip(categorias, contagens):
    print(categoria, ":", quantidade)

Volume de vendas por departamento:
Casa : 21
Eletrônicos : 12
Roupas : 17


**Passo 3 — Campanha campeã**

In [ ]:
faturamento_campanhas = np.array([
    12000,
    45000,
    23000,
    89000,
    31000
])

indice_campea = np.argmax(faturamento_campanhas)

print("Índice da campanha campeã:", indice_campea)
print("Faturamento:", faturamento_campanhas[indice_campea])

Índice da campanha campeã: 3
Faturamento: 89000


## Atividade 2
**Nível 1**

**Passo 1 — 30 dias do mês**

In [ ]:
import numpy as np

dias = np.arange(1, 31)

print(dias)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


**Passo 2 — Metas de vendas**

In [ ]:
metas = np.linspace(20000, 30000, 5)

print("Metas:")
print(metas)

Metas:
[20000. 22500. 25000. 27500. 30000.]


**Passo 3 — Converter para inteiros**

In [ ]:
estoque = np.array([10.5, 20.1, 30.9])

estoque_inteiro = estoque.astype(int)

print("Estoque original:")
print(estoque)

print("Estoque convertido:")
print(estoque_inteiro)

Estoque original:
[10.5 20.1 30.9]
Estoque convertido:
[10 20 30]


**Passo 4 — Últimos cinco dias invertidos**

In [ ]:
ultimos_dias = dias[-5:][::-1]

print("Últimos 5 dias em ordem inversa:")
print(ultimos_dias)

Últimos 5 dias em ordem inversa:
[30 29 28 27 26]


# Nível 2
**Passo 1 — reshape(4, 3)**

In [ ]:
visitas = np.array([
    1200, 1350, 1500,
    1600, 1700, 1800,
    1900, 2000, 2100,
    2200, 2300, 2400
])

trimestres = visitas.reshape(4, 3)

print("Visitas organizadas por trimestre:")
print(trimestres)

Visitas organizadas por trimestre:
[[1200 1350 1500]
 [1600 1700 1800]
 [1900 2000 2100]
 [2200 2300 2400]]


**Passo 2 — vstack()**

In [ ]:
primeiro_semestre = np.array([
    [1200, 1350, 1500],
    [1600, 1700, 1800]
])

segundo_semestre = np.array([
    [1900, 2000, 2100],
    [2200, 2300, 2400]
])

ano_completo = np.vstack([
    primeiro_semestre,
    segundo_semestre
])

print("Dados combinados:")
print(ano_completo)

Dados combinados:
[[1200 1350 1500]
 [1600 1700 1800]
 [1900 2000 2100]
 [2200 2300 2400]]


**Passo 3 — Primeiro trimestre com .copy()**

In [ ]:
primeiro_trimestre = ano_completo[0].copy()

print("Primeiro trimestre:")
print(primeiro_trimestre)

Primeiro trimestre:
[1200 1350 1500]


**Passo 4 — ravel()**

In [ ]:
relatorio = ano_completo.ravel()

print("Array 1D:")
print(relatorio)

Array 1D:
[1200 1350 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400]


# Nível 3
**Passo 1 — Ranking com argsort()**

In [ ]:
notas = np.array([85, 92, 78, 95, 88])

indices = np.argsort(notas)

print("Índices em ordem crescente:")
print(indices)

print("Notas em ordem crescente:")
print(notas[indices])

Índices em ordem crescente:
[2 0 4 1 3]
Notas em ordem crescente:
[78 85 88 92 95]


**Passo 2 — np.newaxis e Broadcasting**

In [24]:
precos = np.array([100, 200, 300])

precos_coluna = precos[:, np.newaxis]

print("Preços em coluna:")
print(precos_coluna)

print("Novo shape:", precos_coluna.shape)

descontos = np.array([0.10, 0.20, 0.30])

precos_com_desconto = precos_coluna * (1 - descontos)

print("Preços com descontos:")
print(precos_com_desconto)

Preços em coluna:
[[100]
 [200]
 [300]]
Novo shape: (3, 1)
Preços com descontos:
[[ 90.  80.  70.]
 [180. 160. 140.]
 [270. 240. 210.]]


**Passo 3 — Sistema com np.linalg.solve()**

In [25]:
A = np.array([
    [2, 1],
    [1, -1]
])

b = np.array([
    500,
    100
])

solucao = np.linalg.solve(A, b)

print("Valor da placa: R$", round(solucao[0], 2))
print("Valor do sensor: R$", round(solucao[1], 2))

Valor da placa: R$ 200.0
Valor do sensor: R$ 100.0
